### ISSUE TITLE
Darcula theme cause crash

### ISSUE THREAD

**Issue by ErickDiniz** [gtasa-savegame-editor/gtasa-savegame-editor#107]
I was looking at the themes, and I was looking for a dark theme, and then I got to Dacula, but then, when I put it in, SaveEditor crashed, it was spamming some blank error screens, and I tried to close and open the SaveEditor, but then it continued with the error, and I can no longer open SaveEditor.

Edit: Now it doesn't open anymore, I went to Appdata and deleted the savegameeditor folder to reset the settings, and after that it doesn't open anymore

```
Crash:java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1368)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1343)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1479)
	at nl.paulinternet.gtasaveedit.view.Main.main(Main.java:68)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "this.loaded" is null
	at nl.paulinternet.gtasaveedit.view.component.TabbedPane.updateUI(TabbedPane.java:110)
	at java.desktop/javax.swing.JTabbedPane.<init>(JTabbedPane.java:231)
	at java.desktop/javax.swing.JTabbedPane.<init>(JTabbedPane.java:196)
	at nl.paulinternet.gtasaveedit.view.component.TabbedPane.<init>(TabbedPane.java:26)
	at nl.paulinternet.gtasaveedit.view.window.MainWindow.createContent(MainWindow.java:49)
	at nl.paulinternet.gtasaveedit.view.GUICreator.run(GUICreator.java:23)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:306)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at nl.paulinternet.gtasaveedit.view.EventQueueProxy.dispatchEvent(EventQueueProxy.java:14)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by lfuelling** [comment]
Hi, which version did you use?

**Comment by ErickDiniz** [comment]
> Hi, which version did you use?

I'm sorry for the delay, it was v3.3-rc.20, I went back to v3.3-rc.19 and it worked on it

**Comment by lfuelling** [comment]
I've released a new version that uses a different theming system: [`v3.3-rc.24`](https://github.com/gtasa-savegame-editor/gtasa-savegame-editor/releases/tag/v3.3-rc.24)
