### ISSUE TITLE
Crush when try to Load

### ISSUE THREAD

**Issue by GrottiHD** [gtasa-savegame-editor/gtasa-savegame-editor#198]
Hello ! Why, no matter what version of the application I'm using, when I try to start it (sometimes) or I try to hit "Load" the application gives me "crush", exactly like in the picture.
I have Java updated to the latest version.
What can i do? Thank you !
![Captură ecran (1)](https://github.com/gtasa-savegame-editor/gtasa-savegame-editor/assets/161250454/5ccb2192-3ee2-4258-9cc5-f4a471358c5e)

**Comment by lfuelling** [comment]
Hey, thanks for reporting!
Could you attach the savegame you are trying to load as a zip?
And is the crash log (the message in the screenshot) the same when it crashes at launch?

**Comment by thefallentoast** [comment]
Mine happens too, but  with a different error.
Log:
`java.lang.IllegalAccessError: class com.github.weisj.darklaf.compatibility.SwingUtil (in unnamed module @0x358cbd13) cannot access class sun.awt.SunToolkit (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x358cbd13
	at com.github.weisj.darklaf.compatibility.SwingUtil.grab(SwingUtil.java:109)
	at com.github.weisj.darklaf.ui.popupmenu.MouseGrabber.grabWindow(MouseGrabber.java:68)
	at com.github.weisj.darklaf.ui.popupmenu.MouseGrabber.stateChanged(MouseGrabber.java:106)
	at java.desktop/javax.swing.MenuSelectionManager.fireStateChanged(Unknown Source)
	at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuUI.appendPath(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Handler.menuDragMouseDragged(Unknown Source)
	at java.desktop/javax.swing.JMenuItem.fireMenuDragMouseDragged(Unknown Source)
	at java.desktop/javax.swing.JMenuItem.processMenuDragMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JMenuItem.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.MenuSelectionManager.processMouseEvent(Unknown Source)
	at com.github.weisj.darklaf.ui.popupmenu.MouseGrabber.eventDispatched(MouseGrabber.java:205)
	at java.desktop/java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Unknown Source)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Unknown Source)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Unknown Source)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Unknown Source)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Unknown Source)
	at java.desktop/java.awt.Toolkit.notifyAWTEventListeners(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at nl.paulinternet.gtasaveedit.view.EventQueueProxy.dispatchEvent(EventQueueProxy.java:14)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at nl.paulinternet.gtasaveedit.view.EventQueueProxy.dispatchEvent(EventQueueProxy.java:21)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
`

**Comment by thefallentoast** [comment]
I've solved it (mine) by changing  the GTA  SA location. Don't forget to apply!

**Comment by lfuelling** [comment]
@GrottiHD it seems like you tried loading either an Android savegame or one of the newer releases that is based on the Android version. The savegame format got changed/updated for the Android Version and any Version built on that, those are currently not supported.
