### ISSUE TITLE
Sudden Unhandled Exception when loading specific Savegame.

### ISSUE THREAD

**Issue by arman-ku** [gtasa-savegame-editor/gtasa-savegame-editor#29]
I am using the .jar Version of the latest release, Win 10 Pro x64.
I loaded up my savegame and selected / deselected some clothings. Because i did some changes i couldnt revert, i wanted to load the savegame again, so i selected Load > Savegame 8.

It threw this:
`java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at nl.paulinternet.gtasaveedit.model.MethodInvoker.handleEvent(MethodInvoker.java:39)
	at nl.paulinternet.gtasaveedit.model.event.ReportableEvent.lambda$report$0(ReportableEvent.java:19)
	at nl.paulinternet.gtasaveedit.model.event.ReportableEvent$$Lambda$15/125993742.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at nl.paulinternet.gtasaveedit.model.event.ReportableEvent.report(ReportableEvent.java:19)
	at nl.paulinternet.gtasaveedit.view.swing.PMenuItem.actionPerformed(PMenuItem.java:31)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.menuDragMouseReleased(BasicMenuItemUI.java:943)
	at javax.swing.JMenuItem.fireMenuDragMouseReleased(JMenuItem.java:586)
	at javax.swing.JMenuItem.processMenuDragMouseEvent(JMenuItem.java:483)
	at javax.swing.JMenuItem.processMouseEvent(JMenuItem.java:429)
	at javax.swing.MenuSelectionManager.processMouseEvent(MenuSelectionManager.java:329)
	at javax.swing.plaf.basic.BasicPopupMenuUI$MouseGrabber.eventDispatched(BasicPopupMenuUI.java:870)
	at java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2425)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2317)
	at java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2275)
	at java.awt.Component.dispatchEventImpl(Component.java:4777)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at nl.paulinternet.gtasaveedit.view.EventQueueProxy.dispatchEvent(EventQueueProxy.java:14)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at nl.paulinternet.gtasaveedit.model.MethodInvoker.handleEvent(MethodInvoker.java:36)
	... 48 more
Caused by: java.lang.RuntimeException: Invalid modID: '65343'!
	at nl.paulinternet.gtasaveedit.model.savegame.data.VehicleMod.getMod(VehicleMod.java:165)
	at nl.paulinternet.gtasaveedit.model.savegame.blocks.Block03.printDebugCsv(Block03.java:181)
	at nl.paulinternet.gtasaveedit.model.savegame.blocks.Block03.load(Block03.java:124)
	at nl.paulinternet.gtasaveedit.model.link.LinkArray.load(LinkArray.java:16)
	at nl.paulinternet.gtasaveedit.model.savegame.Savegame.load(Savegame.java:28)
	at nl.paulinternet.gtasaveedit.view.menu.QuickLoad.loadSavegame(QuickLoad.java:35)
	... 53 more`

savegame is attached.
[GTASAsf8.zip](https://github.com/gtasa-savegame-editor/gtasa-savegame-editor/files/3158465/GTASAsf8.zip)

**Comment by arman-ku** [comment]
ok, pretty sure this is due to the tuned lowrider from the first Cesar Vialpando mission, which i put in my garage. It doesnt have any modifications besides the hydraulics which was already given by the mission. Strange.

I am using the original 1.0 exe from the Hoodlum release and i didnt mod the game in any way other than ENB. All gamefiles are 100% original except for timecycle.dat

**Comment by lfuelling** [comment]
Thanks for your input! And for the attached savegame.

I think it's really the tuned lowrider. The following line hints at this:

`Caused by: java.lang.RuntimeException: Invalid modID: '65343'!`

The modId is currently not inside [`VehicleMods.java`](https://github.com/gtasa-savegame-editor/gtasa-savegame-editor/blob/master/src/main/java/nl/paulinternet/gtasaveedit/model/savegame/data/VehicleMod.java). 

I suspect that the hydraulics added by the ingame script uses a special Id.

**Comment by arman-ku** [comment]
True, i have also figured this out.
Whats funny is that i also cannot access my garage now anymore.
I just used another savegame from the same mission from gtainside
Turns out there is a LOT of unsupported ModIDs. I had to try 3 different savegames.

**Comment by lfuelling** [comment]
Please give them all to me. :) 
I was only able to find the mods that are useable by the player in the GTA wikis.

The only way to fix this unfortunately is to add the missing mods manually after each crash. 
Sorry to hear that it fried your saves :c

**Comment by lfuelling** [comment]
I just published a new release containing the missing mods from the two saves and changes to prevent the crash to occur. 

Thanks for your help 👍
