### ISSUE TITLE
Triggering "Zone Glitch" leads to a NullPointerException

### ISSUE THREAD

**Issue by wahitfitriyanto** [gtasa-savegame-editor/gtasa-savegame-editor#30]
Hello There!
I just found a bug that makes problems occured. When i load "100% Complete savegame" then go to Fixes tab. I see that the zone glitch present status is "Yes" so i click "Fix zone glitch" then the problem that i talking about is occured. Here is the problem from java debug (i think) that i got: 

```
 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at nl.paulinternet.gtasaveedit.model.MethodInvoker.handleEvent(MethodInvoker.java:39)
	at nl.paulinternet.gtasaveedit.model.event.ReportableEvent.lambda$report$0(ReportableEvent.java:19)
	at java.util.ArrayList.forEach(Unknown Source)
	at nl.paulinternet.gtasaveedit.model.event.ReportableEvent.report(ReportableEvent.java:19)
	at nl.paulinternet.gtasaveedit.view.swing.PButton.actionPerformed(PButton.java:31)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at nl.paulinternet.gtasaveedit.view.EventQueueProxy.dispatchEvent(EventQueueProxy.java:14)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at nl.paulinternet.gtasaveedit.model.MethodInvoker.handleEvent(MethodInvoker.java:36)
	... 41 more
Caused by: java.lang.NullPointerException
	at nl.paulinternet.gtasaveedit.model.savegame.ByteSequence.overwrite(ByteSequence.java:133)
	at nl.paulinternet.gtasaveedit.model.GlitchFix.fixZoneGlitch(GlitchFix.java:114)
	at nl.paulinternet.gtasaveedit.view.pages.PageFix.fixZoneGlitch(PageFix.java:121)
	... 46 more
```

So i hope you or anyone else can helping this bug/problem get fix.. 

Note: That problems was occured on both of gtasaveedit (Windows version and java version)

**Comment by lfuelling** [comment]
Hi,
thanks for your report. The fixes are one of the areas I haven't touched so far. 
I'll look into it. Unfortunately I can't say when it will be ready.

**Comment by wahitfitriyanto** [comment]
Hi Lerk! 
Thank you for paying attention to my bug report.  I hope the bug can be fixed as well as possible.  I will wait for further news.  Always successful for you and GTA SA savegame editor. Thank you!

**Comment by lfuelling** [comment]
Hi, I fixed the bug to the extent that it now WorksOnMyMachine™ :)

If you still have problems please simply reopen the issue.

**Comment by AKD92** [comment]
Hi I have a question regarding this exception. Is there a way to corrupt current save game data loaded on memory by this exception? For example, on a loaded save game data we hit Zone Glitch Fix and the exception occured, resulting the opened save game data corrupted somehow. Then if we save it, corrupted data gets back to the file. Any possibility? I am facing this kind of anomaly but not sure about the source of the problem, using Savegame Editor v3.2.
