### ISSUE TITLE
doesn't open in linux [ubutntu] 

### ISSUE THREAD

**Issue by darkRaspberry** [gtasa-savegame-editor/gtasa-savegame-editor#74]
I always see this error why! 😢 
I tried 32 bit, 64 bit.

```java
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at nl.paulinternet.gtasaveedit.view.Main.main(Main.java:22)
Caused by: java.lang.UnsatisfiedLinkError: /home/dev/Downloads/GTA SA Savegame Editor 3.2 - Linux 32-bit/libgluegen-rt.so: /home/dev/Downloads/GTA SA Savegame Editor 3.2 - Linux 32-bit/libgluegen-rt.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2659)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:442)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:59)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:90)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:328)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:390)
	at com.jogamp.common.os.Platform.loadGlueGenRTImpl(Platform.java:251)
	at com.jogamp.common.os.Platform.access$000(Platform.java:57)
	at com.jogamp.common.os.Platform$1.run(Platform.java:186)
	at com.jogamp.common.os.Platform$1.run(Platform.java:183)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:183)
	at javax.media.opengl.GLProfile.<clinit>(GLProfile.java:82)
	at jogamp.opengl.ThreadingImpl$1.run(ThreadingImpl.java:90)
	at jogamp.opengl.ThreadingImpl$1.run(ThreadingImpl.java:74)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at jogamp.opengl.ThreadingImpl.<clinit>(ThreadingImpl.java:73)
	at javax.media.opengl.Threading.disableSingleThreading(Threading.java:138)
	at javax.media.j3d.JoglPipeline.initialize(JoglPipeline.java:117)
	at javax.media.j3d.Pipeline.createPipeline(Pipeline.java:89)
	at javax.media.j3d.MasterControl.loadLibraries(MasterControl.java:832)
	at javax.media.j3d.VirtualUniverse.<clinit>(VirtualUniverse.java:274)
	at javax.media.j3d.GroupRetained.<init>(GroupRetained.java:155)
	at javax.media.j3d.BranchGroupRetained.<init>(BranchGroupRetained.java:50)
	at javax.media.j3d.BranchGroup.createRetained(BranchGroup.java:71)
	at javax.media.j3d.SceneGraphObject.<init>(SceneGraphObject.java:114)
	at javax.media.j3d.Node.<init>(Node.java:172)
	at javax.media.j3d.Group.<init>(Group.java:549)
	at javax.media.j3d.BranchGroup.<init>(BranchGroup.java:63)
	at nl.paulinternet.gtasaveedit.view.cloth.ShapeViewer.<init>(ShapeViewer.java:47)
	at nl.paulinternet.gtasaveedit.view.pages.PageClothes.<init>(PageClothes.java:85)
	at nl.paulinternet.gtasaveedit.view.TabbedPane.<init>(TabbedPane.java:31)
	at nl.paulinternet.gtasaveedit.view.Window.createContent(Window.java:48)
	at nl.paulinternet.gtasaveedit.view.GUICreator.run(GUICreator.java:30)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at nl.paulinternet.gtasaveedit.view.EventQueueProxy.dispatchEvent(EventQueueProxy.java:12)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by darkRaspberry** [comment]
Even in sudo mode

```shell
dev@ubu27x:~/Downloads/gtasansave$ sudo ./editor
[sudo] password for dev: 
Catched NoSuchFileException: /home/dev/Downloads/gtasansave/editor-natives-linux-amd64.jar, while TempJarCache.bootstrapNativeLib() of jar:file:/home/dev/Downloads/gtasansave/editor-natives-linux-amd64.jar!/ (file:/home/dev/Downloads/gtasansave/ + editor-natives-linux-amd64.jar)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jogamp.common.os.NativeLibrary$3 (file:/home/dev/Downloads/gtasansave/editor.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.jogamp.common.os.NativeLibrary$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
OpenJDK 64-Bit Server VM warning: You have loaded library /home/dev/Downloads/gtasansave/libgluegen-rt.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```

**Comment by lfuelling** [comment]
Hi, 

To fix the exception in the issue description you might need to install the [libjogl-java](http://archive.ubuntu.com/ubuntu/ubuntu/pool/universe/libj/libjogl-java/) package, although that functionality (afaik) comes bundled with your JRE. 

I'm not really sure where `gtasansave/editor-natives-linux-amd64.jar` comes from though, this file don't seem to belong to this project. Judging by the path `GTA SA Savegame Editor 3.2`, I'd assume that you are trying to use the older version available at paulinternet.nl - please try using the [latest release](https://github.com/gtasa-savegame-editor/gtasa-savegame-editor/releases) of this project if possible.

**Comment by darkRaspberry** [comment]
One short doubt. can i skip current mission by this app? Because if it does then its just supper cool.

**Comment by darkRaspberry** [comment]
Also sorry to say that--
I'm on Ubuntu 20.10 And i use updated dependencies and all. But this `.deb` file which you are including in release is too hard to install and uninstall.
The basic rule to install this `.deb` to my system is in one single shot. First install dependencies then install the .deb. If you reversed it then.

```shell
dev@ubu27x:~/Downloads/GTA.SA-Savegame-Editor.deb/deploy$ sudo dpkg -i savegame-editor_3.3~SNAPSHOT_all.deb
Selecting previously unselected package gtasa-savegame-editor.
(Reading database ... 211767 files and directories currently installed.)
Preparing to unpack savegame-editor_3.3~SNAPSHOT_all.deb ...
Unpacking gtasa-savegame-editor (3.3~SNAPSHOT) ...
dpkg: dependency problems prevent configuration of gtasa-savegame-editor:
 gtasa-savegame-editor depends on openjdk-8-jre; however:
  Package openjdk-8-jre is not installed.

dpkg: error processing package gtasa-savegame-editor (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 gtasa-savegame-editor
dev@ubu27x:~/Downloads/GTA.SA-Savegame-Editor.deb/deploy$ sudo apt install openjdk-8-jre
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 openjdk-8-jre : Depends: openjdk-8-jre-headless (= 8u275-b01-0ubuntu1~20.10) but it is not going to be installed
                 Depends: libatk-wrapper-java-jni (>= 0.33.3-9~) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
dev@ubu27x:~/Downloads/GTA.SA-Savegame-Editor.deb/deploy$ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  ca-certificates-java java-common libatk-wrapper-java libatk-wrapper-java-jni openjdk-8-jre openjdk-8-jre-headless
Suggested packages:
  default-jre icedtea-8-plugin fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei fonts-wqy-zenhei
The following NEW packages will be installed:
  ca-certificates-java java-common libatk-wrapper-java libatk-wrapper-java-jni openjdk-8-jre openjdk-8-jre-headless
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 28.4 MB of archives.
After this operation, 104 MB of additional disk space will be used.
Do you want to continue? [Y/n] y

...skipping install lines

Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
Errors were encountered while processing:
 gtasa-savegame-editor
E: Sub-process /usr/bin/dpkg returned an error code (1)
dev@ubu27x:~/Downloads/GTA.SA-Savegame-Editor.deb/deploy$ sudo dpkg -i savegame-editor_3.3~SNAPSHOT_all.deb
(Reading database ... 212063 files and directories currently installed.)
Preparing to unpack savegame-editor_3.3~SNAPSHOT_all.deb ...
Removing desktop entry...
rm: cannot remove '/usr/share/applications/gtasa-savegame-editor.desktop': No such file or directory
Removing shell shortcut...
rm: cannot remove '/usr/bin/gtasa-savegame-editor': No such file or directory
dpkg: warning: old gtasa-savegame-editor package pre-removal script subprocess returned error exit status 1
dpkg: trying script from the new package instead ...
Removing desktop entry...
rm: cannot remove '/usr/share/applications/gtasa-savegame-editor.desktop': No such file or directory
Removing shell shortcut...
rm: cannot remove '/usr/bin/gtasa-savegame-editor': No such file or directory
dpkg: error processing archive savegame-editor_3.3~SNAPSHOT_all.deb (--install):
 new gtasa-savegame-editor package pre-removal script subprocess returned error exit status 1
dpkg: error while cleaning up:
 installed gtasa-savegame-editor package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 savegame-editor_3.3~SNAPSHOT_all.deb
dev@ubu27x:~/Downloads/GTA.SA-Savegame-Editor.deb/deploy$ sudo dpkg -r gtasa-savegame-editor 
dpkg: error processing package gtasa-savegame-editor (--remove):
 package is in a very bad inconsistent state; you should
 reinstall it before attempting a removal
Errors were encountered while processing:
 gtasa-savegame-editor

``` 

SEE if i try uninstall and it struck. Even with force uninstall it says package is inconsistent. Please install it again but ...you can't install it again.

I just wanted to edit the save game to just skip a mission exactly without affecting any changes. BUT  although old version may be `v3.3-rc.9` to `v3.3-rc.12` opened. I don't rem exactly which version. (So i closed the issue)
But After opening it says update the deb file and I updated the deb file then dpkg again showed error. I used many version and save game to test may apps on Linux/wine/vm  Eventually lost my main save game (The one i created by passing mission) Then in frustration i deleted everything.

I play the game on wine for Linux. But that's not your issue.

**Comment by darkRaspberry** [comment]
I play the game on wine for Linux. But that's not your issue. 
I even try building the project with `mvn clean package -Pdeb` But after completing all required dependencies it fails to build. 

If this app can skip mission then its super cool. I read about much how save game work. And i think `block 0` and `block 18` contain some mission info. but i don't know. HOW to skip,

**Comment by lfuelling** [comment]
> can i skip current mission by this app?

No that is not possible (yet).

> i use updated dependencies and all

Sorry, that is indeed a bug, I have opened #75 for it.

> Even with force uninstall it says package is inconsistent

And another bug 🙈 
I have opened #76 for it.

> If this app can skip mission then its super cool.

That would indeed be really cool.

>  I read about much how save game work. And i think block 0 and block 18 contain some mission info. but i don't know. HOW to skip,

My guess would be that it's necessary to collect all needed parameters for the each mission (so analysing the savegame blocks each time the mission changes) [into the docs](https://github.com/gtasa-savegame-editor/docs) and then build a dropdown using that data.
Unfortunately I'm not very good at analysing binary data, that's also why the Android support (#4) is taking so long.

**Comment by darkRaspberry** [comment]
Thanks for creating 2 issues. I have saw mvn for at most one repo except this. May be they work good (in GitHub actions) but in Linux they don't.
I know that these app don't pay your bills. And I'm somehow willing to collect that binary data and process it. So that this app can skip mission. Also I m not professional but I'm fast learner. All i need to know is how to collect and how to store and process it. I will keep you updated. I now need a original GTA game and start working..

**Comment by lfuelling** [comment]
> Thanks for creating 2 issues. I have saw mvn for at most one repo except this. May be they work good (in GitHub actions) but in Linux they don't.

`mvn` is actually called [Maven](https://maven.apache.org/) and is a build tool for Java applications. 
As I said, the debian package is currently broken (because of outdated metadata) but building without the `-P` parameter (so just running `mvn clean install` should work on every operating system. This will create a `savegame-editor-jar-with-dependencies.jar` file that you can run from the command line (`java -jar path/to/editor/target/savegamge-editor-jar-with-dependencies.jar`) or by double clicking it (you need a compatible java version/java launcher).

> And I'm somehow willing to collect that binary data and process it.

That would be nice. Unfortunately I can't really help you with questions about the savegames that go beyond information that is already listed in the docs. 
If you have questions about the editor application itself, I can of course help.

> I guess firstly this app need a new deb build/release generator or may be shell script or bundle or standalone app

Not really. The `.deb` profile for Maven works fine as it is, the only thing I need to do is to update the dependencies (the application needs java 11 instead of 8) and add some sort of error handling to the preinstall and postinstall scripts. 
Regardless of the method used to build the deb, it will still fail all the time, because the error is in the [`.deb` Metadata](https://github.com/gtasa-savegame-editor/gtasa-savegame-editor/tree/main/savegame-editor/src/deb/control).

You can also take a look at the release page, there are binaries for Windows, macOS and a cross-platform `.jar` file as well as the (broken) deb and rpm files.

**Comment by darkRaspberry** [comment]
👍🏻

**Comment by lfuelling** [comment]
Hi again, 

Regarding your original issue, could you please try if [`v3.3-rc.19`](https://github.com/gtasa-savegame-editor/gtasa-savegame-editor/releases/tag/v3.3-rc.19) fixes the `.deb` installation for you?

**Comment by darkRaspberry** [comment]
Working on it

**Comment by darkRaspberry** [comment]
Downloaded the deb version and double clicked it
![Screenshot from 2021-03-20 13-44-41](https://user-images.githubusercontent.com/56693429/111863747-626d8d80-8983-11eb-96bd-94ef88476318.png)
But that's not a issue. Because the application ask to create a shortcut so post installation failed. We all use dpkg in Linux in that case and it works fine.


![Screenshot from 2021-03-20 13-46-22](https://user-images.githubusercontent.com/56693429/111863771-7ca76b80-8983-11eb-9c73-4ae55afeb423.png)
Application works. And ask me to use a updated version. But it works really fine.

This is terminal dumb.

```shell
dev@ubu27x:~/Downloads/GTA.SA-Savegame-Editor.deb/deploy$ la
savegame-editor_3.3.0~SNAPSHOT_all.deb
dev@ubu27x:~/Downloads/GTA.SA-Savegame-Editor.deb/deploy$ sudo dpkg -i *.deb
[sudo] password for dev: 
(Reading database ... 195639 files and directories currently installed.)
Preparing to unpack savegame-editor_3.3.0~SNAPSHOT_all.deb ...
Unpacking gtasa-savegame-editor (3.3.0~SNAPSHOT) over (3.3.0~SNAPSHOT) ...
Setting up gtasa-savegame-editor (3.3.0~SNAPSHOT) ...
Creating shell shortcut...
You can start the editor by running: gtasa-savegame-editor
dev@ubu27x:~/Downloads/GTA.SA-Savegame-Editor.deb/deploy$ gtasa-savegame-editor

Gtk-Message: 13:45:35.095: Failed to load module "canberra-gtk-module"
[main] INFO nl.paulinternet.gtasaveedit.Settings - Config directory created!
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '23' (Esplanade North garage used in "Ran Fa Li"), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '24' (Downtown garage used in "Yay Ka-Boom-Boom"), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '25' (Angel Pine garage used in "Puncture Wounds"), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '26' (Redsands East Pay n Spray), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '27' (Welding and Wedding bomb shop), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '28' (Los Santos Transfender), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '29' (San Fierro burglary garage), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '30' (Los Santos burglary garage), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '31' (Dillimore Pay n Spray), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '32' (Fort Carson Pay n Spray), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '33' (El Quebrados Pay n Spray), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '34' (El Corona garage used in "Los Desperados"), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '35' (Wu Zi's garage), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '36' (El Castillo del Diablo garage used in "Interdiction"), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '37' (Los Santos bomb shop), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '38' (Doherty garage), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '39' (San Fierro Transfender), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '40' (Michelle's garage), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '41' (Cesar's garage), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '42' (Downtown Los Santos garage used in "Life's a Beach"), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '43' (Idlewood Pay n Spray), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '44' (Temple Pay n Spray), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '45' (Verona Beach Pay n Spray), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '46' (Downtown San Fierro Pay n Spray), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '47' (Juniper Hollow Pay n Spray), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '48' (Ocean Flat garage used in "T-Bone Mendez"), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '49' (Las Venturas unused Pay n Spray), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '50' (Las Venturas Transfender), skipping...
[AWT-EventQueue-0] WARN nl.paulinternet.gtasaveedit.view.pages.PageGarages - No garageId set for garage at position '51' (Las Venturas burglary garage), skipping...

dev@ubu27x:~/Downloads/GTA.SA-Savegame-Editor.deb/deploy$ sudo dpkg --remove gtasa-savegame-editor
(Reading database ... 195639 files and directories currently installed.)
Removing gtasa-savegame-editor (3.3.0~SNAPSHOT) ...
Removing shell shortcut...
dev@ubu27x:~/Downloads/GTA.SA-Savegame-Editor.deb/deploy$ gtasa-savegame-editor\
> ^C
dev@ubu27x:~/Downloads/GTA.SA-Savegame-Editor.deb/deploy$ gtasa-savegame-editor
bash: /usr/bin/gtasa-savegame-editor: No such file or directory
dev@ubu27x:~/Downloads/GTA.SA-Savegame-Editor.deb/deploy$ 


```

**Comment by lfuelling** [comment]
Thanks for the feedback! 
The available updates dialog seems to be buggy I have added #86 for this.

**Comment by lfuelling** [comment]
Hi, sorry that this took so long. 
Could you try it again with [`v3.3-rc.23`](https://github.com/gtasa-savegame-editor/gtasa-savegame-editor/releases/tag/v3.3-rc.23)?

**Comment by darkRaspberry** [comment]
Hi, So thanks for making this happen. I tested jar file and it works out of the box. No config required. Further I see no matter where you are in the app. If you tap on `about` then it starts play the audio. If it already playing then it restart the audio. Look like when user click on it. It triggers audio to start playing.

If you want log then leave a ping.

**Comment by darkRaspberry** [comment]
Further Don't take this wrong or be offended. But your app has a dependencies of java or JRE. Then why are creating binary. Because when installing it explicitly ask for JRE dependencies.

Simply release a .jar file and that's it. I don't know about windows but in Linux I need to install whole jre dependencies when I installed the deb file.

May be stop release these binary and focus on the app itself. You can release a well documented way how to run JRE. I can help.

**Comment by lfuelling** [comment]
Thanks for your feedback. The behavior of the audio is as designed. 

You should be able to see the menubar, from where you can load savegames; the location depends on your operating system (on Windows it's attached to the window, on macOS it's attached to the top of the screen, Linux can do both and more).

The reason for the binaries was actually user friendlyness, on Debian the JRE would be installed by the package dependencies, on macOS I have the ability to bundle the JRE into the `.app` (although I only want to do that on releases because it makes the app huge) and on Windows, the openjdk download page will be opened if no JRE could be found. 
I also planned to bundle the JRE on Windows but that would require creating an installer, unfortunately any Java compatible installer framework is either very expensive, not automatable, or no longer maintained.

The jar is still attached to the releases, but you're right in the regard that I could add a section to the README explaining this.

**Comment by darkRaspberry** [comment]
See this. When directly installing the `.deb` without any terminal
![Screenshot from 2022-01-06 23-53-58](https://user-images.githubusercontent.com/56693429/148433570-45b23b34-ff15-4909-a251-9fc0cd92e6f9.png)

The post installation script is causing the issue.

Further after installing the depencidence I installed with the terminal and it installed one time successfully and then completed post installation script (In which it create shortcut to desktop.)

Further installation of the same `.deb` again (aka dirty installs) fails and fails continuously. Here post installations failed. Means After dirty installation post installation failed. 

Uninstall is super clean no issue I can see. (Although I installed the app and run post install script then uninstalled.)

**Comment by lfuelling** [comment]
I've published new release with a fixed install script: [`v3.3-rc.24`](https://github.com/gtasa-savegame-editor/gtasa-savegame-editor/releases/tag/v3.3-rc.24)
