### ISSUE TITLE
Flight School not saving properly.

### ISSUE THREAD

**Issue by walale12** [gtasa-savegame-editor/gtasa-savegame-editor#81]
I have legitimately obtained gold medals in the flying school in all categories except the helicopter shooting one, in which I have 96%.
When I load the save in the editor, and change it to 100%, I can save the file just fine, and load it, but when I go to the TV in the flight school, it still says I only have 96% in the challenge, despite the save editor saying I have 100% when I load the save in the editor.

**Comment by walale12** [comment]
It pops up this error when I try and edit the value of the helicopter shooting challenge:
An Error has occurred
`java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at nl.paulinternet.gtasaveedit.event.MethodInvoker.handleEvent(MethodInvoker.java:33)
	at nl.paulinternet.gtasaveedit.event.ReportableEvent.lambda$report$0(ReportableEvent.java:19)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at nl.paulinternet.gtasaveedit.event.ReportableEvent.report(ReportableEvent.java:19)
	at nl.paulinternet.gtasaveedit.view.swing.PTextField.removeUpdate(PTextField.java:63)
	at java.desktop/javax.swing.text.AbstractDocument.fireRemoveUpdate(AbstractDocument.java:261)
	at java.desktop/javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:628)
	at java.desktop/javax.swing.text.AbstractDocument.remove(AbstractDocument.java:596)
	at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:672)
	at java.desktop/javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1339)
	at java.desktop/javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(DefaultEditorKit.java:884)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2900)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2948)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
	at java.desktop/java.awt.Component.processEvent(Component.java:6412)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4892)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at nl.paulinternet.gtasaveedit.view.EventQueueProxy.dispatchEvent(EventQueueProxy.java:14)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at nl.paulinternet.gtasaveedit.event.MethodInvoker.handleEvent(MethodInvoker.java:31)
	... 46 more
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at nl.paulinternet.libsavegame.variables.Variable.setText(Variable.java:81)
	at nl.paulinternet.gtasaveedit.view.connected.ConnectedTextField.updateToModel(ConnectedTextField.java:53)
	... 50 more
`

**Comment by lfuelling** [comment]
Thanks for reporting this. It might be related to #72.

Would you mind attaching the savefile?

**Comment by walale12** [comment]
[GTASave.zip](https://github.com/gtasa-savegame-editor/gtasa-savegame-editor/files/6168745/GTASave.zip)
I've attached a .zip containing my save file
